variables:
  CI_CONF_DIR: .config/ci
  SHELLCHECK_VER: v0.9.0

.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "validate-schedule-workflow" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - test
  - sync

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:$SHELLCHECK_VER
  before_script:
    - apk update
    - apk add git xmlstarlet
    - shellcheck --version
  script:
    - git ls-files --exclude='*.sh' --ignored -c -z |
      xargs -t --no-run-if-empty -0 shellcheck --format=checkstyle |
      xmlstarlet tr $CI_CONF_DIR/shellcheck/checkstyle2junit.xslt >
      shellcheck.xml
  artifacts:
    when: always
    reports:
      junit: shellcheck.xml
  rules:
    - !reference [.default_rules, rules]

sync-master:
  stage: sync
  image:
    name: bitnami/git:2.43.0
  before_script:
    - git config --global http.sslVerify false
  script:
    - mkdir spdk && cd spdk
    - git clone --branch $GITHUB_BRANCH $SPDK_URL .
    - git remote rename origin old-origin
    - git remote add origin https://$CI_USERNAME:$CI_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git 
    - git push origin $GITHUB_BRANCH:$GITLAB_BRANCH
    - git push -u origin --tags
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "sync"
    - when: manual && $SCHEDULE_TYPE == "sync"
  variables:
    GIT_STRATEGY: none
    SPDK_URL: https://github.com/OpenMPDK/DSS
    GITHUB_BRANCH: master
    GITLAB_BRANCH: validate-schedule-workflow
