include: .config/ci/gitlab/defaults.yml

stages:
  - test
  - sync

shellcheck:
  stage: test
  trigger:
    include:
      - local: $GITLAB_CONF_DIR/shellcheck.yml
    strategy: depend
  rules:
    - !reference [.default_rules, merge_push_rules]

sync-github:
  stage: sync
  trigger:
    include:
      - local: $GITLAB_CONF_DIR/sync-github.yml
    strategy: depend
  rules:
    - !reference [.default_rules, sync_rules]
  allow_failure: true
  variables:
    GITHUB_REPO: DSS
