include:
  - local: .config/ci/gitlab/defaults.yml
  - local: .config/ci/gitlab/shellcheck.yml
  - local: .config/ci/gitlab/sync-github.yml

stages:
  - test
  - sync

sync-github:
  variables:
    GITHUB_REPO: DSS
