variables:
  CI_CONF_DIR: .config/ci

include: $CI_CONF_DIR/gitlab/defaults.yml

stages:
  - test
  - sync

shellcheck:
  stage: test
  trigger:
    include:
      - local: $CI_CONF_DIR/gitlab/shellcheck.yml
  rules:
    - !reference [.default_rules, rules]

sync-github:
  stage: sync
  trigger:
    include:
      - local: $CI_CONF_DIR/gitlab/sync-github.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "sync"
    - when: manual
  variables:
    GITHUB_PROJECT: OpenMPDK
    GITHUB_REPO: DSS
    GITHUB_BRANCH: master
    GITLAB_BRANCH: master
