variables:
  CI_CONF_DIR: .config/ci
  SHELLCHECK_VER: v0.9.0

.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "validate-schedule-workflow" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - test
  - sync

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:$SHELLCHECK_VER
  before_script:
    - apk update
    - apk add git xmlstarlet
    - shellcheck --version
  script:
    - git ls-files --exclude='*.sh' --ignored -c -z |
      xargs -t --no-run-if-empty -0 shellcheck --format=checkstyle |
      xmlstarlet tr $CI_CONF_DIR/shellcheck/checkstyle2junit.xslt >
      shellcheck.xml
  artifacts:
    when: always
    reports:
      junit: shellcheck.xml
  rules:
    - !reference [.default_rules, rules]

sync-github:
  stage: sync
  trigger:
    include:
      - local: $CI_CONF_DIR/gitlab/sync-github.yml
  variables:
    GITHUB_PROJECT: OpenMPDK
    GITHUB_REPO: DSS
    GITHUB_BRANCH: master
    GITLAB_BRANCH: master
