name: Build
on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master
env:
  GH_PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
